// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.linux:
        // Note: To find out if you are using the Tizen platform, refer to the link below.
        // https://github.com/flutter-tizen/flutter-tizen/issues/482#issuecomment-1441139704
        return tizen;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // For firebase_storage test
  static FirebaseOptions get baseOptions {
    return FirebaseOptions(
      apiKey: 'PLACEHOLDER',
      appId: 'PLACEHOLDER',
      messagingSenderId: 'PLACEHOLDER',
      projectId: 'PLACEHOLDER',
      databaseURL: 'PLACEHOLDER',
      storageBucket: 'PLACEHOLDER',
    );
  }

  static const FirebaseOptions tizen = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'PLACEHOLDER',
    databaseURL: 'PLACEHOLDER',
    storageBucket: 'PLACEHOLDER',
  );

  static String get emulatorHost {
    return 'PLACEHOLDER';
  }
}
