name: firebase_core_tizen
description: Flutter plugin for Firebase Core, enabling connecting to multiple
  Firebase apps.
version: 1.0.1
homepage:

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_core: ^2.17.0
  firebase_core_platform_interface: ^4.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pigeon: 9.2.5

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: FirebaseCoreTizenPlugin
        fileName: firebase_core_tizen_plugin.h
