name: firebase_core_tizen
description: Flutter plugin for Firebase Core, enabling connecting to multiple
  Firebase apps.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_core: 2.4.1
  firebase_core_platform_interface: 4.5.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^3.2.9

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: FirebaseCoreTizenPlugin
        fileName: firebase_core_tizen_plugin.h
