name: cloud_functions_tizen
description: The Firebase Cloud Functions implementation for Tizen.
version: 0.1.0
homepage:
repository:
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cloud_functions: 4.0.7
  cloud_functions_platform_interface: 5.1.26
  firebase_core_tizen: ^1.0.1
  flutter:
    sdk: flutter

dependency_overrides:
  firebase_core_tizen:
    path: ../firebase_core

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: cloud_functions
    platforms:
      tizen:
        pluginClass: CloudFunctionsPlugin
        fileName: cloud_functions_plugin.h
