name: firebase_database_tizen
description: The Firebase Database implementation for Tizen.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_core_tizen: ^1.0.0
  firebase_database: 10.0.9
  firebase_database_platform_interface: 0.2.2+17
  flutter:
    sdk: flutter

dependency_overrides:
  firebase_core_tizen:
    path: ../firebase_core

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: firebase_database
    platforms:
      tizen:
        pluginClass: FirebaseDatabaseTizenPlugin
        fileName: firebase_database_tizen_plugin.h
