name: Integration Test

on:
  pull_request:
  push:
    branches:
      - main
      - dev/ci

jobs:
  integration_test:
    runs-on: [self-hosted]
    if: ${{ github.repository_owner == 'flutter-tizen' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64
      - run: flutter --version
      - name: Install flutter-tizen
        uses: actions/checkout@v3
        with:
          repository: flutter-tizen/flutter-tizen
          path: flutter-tizen
          fetch-depth: 1
      - name: Set firebase options
        run: |
          bash ${{ secrets.PRE_INSTALLER }}
      - name: Run tests
        run: |
          export PATH=`pwd`/flutter-tizen/bin:$PATH
          ./tools/tools_runner.sh integration-test --generate-emulators --recipe ./.github/recipe.yaml
